CONTIKI_TARGET_SOURCEFILES += contiki-avr-derfmega128-platform.c \
	sht11.c sht11-sensor.c light-sensor.c battery-sensor.c \
	button-sensor.c radio-sensor.c

#ifndef SMALL
#SMALL=1
#endif

include $(CONTIKI)/platform/avr-derfmega128/Makefile.common

