CONTIKI = ../..

all: example-abc.elf example-mesh.elf example-collect.elf example-trickle.elf example-polite.elf \
     example-rudolph0.elf example-rudolph1.elf example-rudolph2.elf example-rucb.elf \
     example-runicast.elf example-unicast.elf example-neighbors.elf

include $(CONTIKI)/Makefile.include
