### The RF230 "bare bones" driver uses the core MAC layer.
### It is required for versions after contiki 2.4 that use the new driver interfaces

ifndef RF230BB
RF230BB=1
endif

### Define RF230BB in the base makefile, or use $make RF230BB=1 ...
ifeq ($(RF230BB),1)
  CFLAGS                     += -DRF230BB
  #Source for AT86RF230 barebones driver using the contiki core MAC
  include $(CONTIKI)/cpu/arm/lm3s9b96/radio/rf230bb/Makefile.rf230bb
endif
